package com.example.SimpleCRUDAPI.entity;

// jakarta persistence gives the @
import jakarta.persistence.*;

@Entity
@Table(name = "users")
public class User {
    // The @Id annotation is used to specify the primary key of an entity. 
    @Id
    // The @GeneratedValue annotation is used to specify the primary key generation strategy to use. The GenerationType.IDENTITY strategy is used to specify that the primary key is generated by the database. The primary key is automatically generated by the database when a new row is inserted into the table.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false)
    private String password;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
